version: '3.7'

services:
    myapp:
        build:
            context: ./
            dockerfile: Dockerfile
        image: myapp
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './:/var/www/html'
        networks:
            - myapp
networks:
    myapp:
        driver: bridge
volumes:
    mysql:
        driver: local

